FOURSTAR -ASP NET/WebApplication1/WebApplication1/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.DAO;
using MySql.Data.MySqlClient;

namespace WebApplication1.Models
{
    public class Filme
    {


        public List<filmespojo> listarinfo()

        {
            List<filmespojo> listafilmes = new List<filmespojo>();

            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();

            string query = "SELECT * FROM filmes";



            //create command and assign the query and connection from the constructor

            cmd.CommandText = query;

            MySqlDataReader Reader = cmd.ExecuteReader();

            while (Reader.Read())
            {
                filmespojo f = new filmespojo();
                f.cod = Reader.GetString(0);
                f.nome = Reader.GetString(1);
                f.genero = Reader.GetString(2);
                f.duracao = Reader.GetString(3);
                f.diretor = Reader.GetString(4);
                f.imagemref = Reader.GetString(5);
                f.imdbrating = Reader.GetString(6);
                f.videoref = Reader.GetString(7);


                listafilmes.Add(f);
            }

            cmd.Dispose();
            objCon.CloseConnection();



            //Execute command
            // cmd.ExecuteNonQuery();

            //close connection
            cmd.Dispose();
            // conexao.close();


            return listafilmes;




        }

        public List<filmespojo> listarcomedia()

        {
            List<filmespojo> listafilmes = new List<filmespojo>();

            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();
            string query = "SELECT * FROM filmes where genero='Comédia'";

            cmd.CommandText = query;



            //create command and assign the query and connection from the constructor


            MySqlDataReader Reader = cmd.ExecuteReader();

            while (Reader.Read())
            {
                filmespojo f = new filmespojo();
                f.cod = Reader.GetString(0);
                f.nome = Reader.GetString(1);
                f.genero = Reader.GetString(2);
                f.duracao = Reader.GetString(3);
                f.diretor = Reader.GetString(4);
                listafilmes.Add(f);
            }



            //Execute command
            // cmd.ExecuteNonQuery();

            //close connection

            cmd.Dispose();
            objCon.CloseConnection();

            return listafilmes;




        }




        public void inserirfilme(filmespojo filme)

        {

            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();
            string query = "INSERT INTO filmes (cod, nome, genero, duracao, diretor,imagemref,nota,videoref) VALUES('" + filme.cod + "', '" + filme.nome + "','" + filme.genero + "','" + filme.duracao + "','" + filme.diretor + "','" + filme.imagemref + "','" + filme.imdbrating + "','" + filme.videoref +"')";

            cmd.CommandText = query;

            //create command and assign the query and connection from the constructor


            //Execute command
            cmd.ExecuteNonQuery();

            //close connection
            cmd.Dispose();
            objCon.CloseConnection();





        }

        public bool inserirassistidos(filmespojo filme, PessoaPojo pessoa)

        {
            int opcao = 0;

            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmdverificar = Conn.CreateCommand();

            string queryverificar = "SELECT status FROM meufilme WHERE pessoaid='" + pessoa.Id + "'and filmeid='" + filme.cod + "'";

            cmdverificar.CommandText = queryverificar;

            MySqlDataReader Reader = cmdverificar.ExecuteReader();

            while (Reader.Read())
            {
                if (Reader.HasRows == true)
                {
                    if (Reader.GetInt32(0) == 0) { opcao = 1; }
                    else opcao = 2;
                }
            }

            cmdverificar.Dispose();

            objCon.CloseConnection();

            if (opcao == 1)
            {
                Conn = objCon.OpenConnection();
                MySqlCommand cmdupdate = Conn.CreateCommand();

                string queryupdate = "UPDATE meufilme SET status='1' WHERE pessoaid='" + pessoa.Id + "'and filmeid='" + filme.cod + "' and status='0'";

                cmdupdate.CommandText = queryupdate;

                cmdupdate.ExecuteNonQuery();
                cmdupdate.Dispose();
                objCon.CloseConnection();
                return true;

            }

            if (opcao == 2) return false;

            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();
            string query = "INSERT INTO meufilme (pessoaid, filmeid, status) VALUES('" + pessoa.Id + "', '" + filme.cod + "','1')";


            //create command and assign the query and connection from the constructor
            cmd.CommandText = query;

            //Execute command
            cmd.ExecuteNonQuery();

            //close connection
            cmd.Dispose();
            objCon.CloseConnection();



            return true;

        }


        public bool inserirdesejos(filmespojo filme, PessoaPojo pessoa)

        {
            int opcao = 0;

            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmdverificar = Conn.CreateCommand();

            string queryverificar = "SELECT status FROM meufilme WHERE pessoaid='" + pessoa.Id + "'and filmeid='" + filme.cod + "'";
            cmdverificar.CommandText = queryverificar;

            MySqlDataReader Reader = cmdverificar.ExecuteReader();

            while (Reader.Read())
            {
                if (Reader.HasRows == true)
                {
                    opcao = 1;
                }
            }

            cmdverificar.Dispose();
            objCon.CloseConnection();


            if (opcao == 1)
            {
                return false;

            }


            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();

            string query = "INSERT INTO meufilme (pessoaid, filmeid, status) VALUES('" + pessoa.Id + "', '" + filme.cod + "','0')";


            //create command and assign the query and connection from the constructor
            cmd.CommandText = query;

            //Execute command
            cmd.ExecuteNonQuery();

            //close connection
            cmd.Dispose();
            objCon.CloseConnection();



            return true;

        }



        public filmespojo selecionarfilme(filmespojo filmecod)

        {


            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();

            string query = "SELECT * FROM filmes where cod='" + filmecod.cod + "'";

            filmespojo f = new filmespojo();


            //create command and assign the query and connection from the constructor
            cmd.CommandText = query;

            MySqlDataReader Reader = cmd.ExecuteReader();

            while (Reader.Read())
            {

                f.cod = Reader.GetString(0);
                f.nome = Reader.GetString(1);
                f.genero = Reader.GetString(2);
                f.duracao = Reader.GetString(3);
                f.diretor = Reader.GetString(4);
                f.videoref = Reader.GetString(7);

            }



            //Execute command
            // cmd.ExecuteNonQuery();

            //close connection

            cmd.Dispose();
            objCon.CloseConnection();
            return f;




        }


        public List<filmespojo> listarassistidos(int id)

        {


            Conexao objCon = new Conexao();
            MySqlConnection Conn = new MySqlConnection();
            Conn = objCon.OpenConnection();
            MySqlCommand cmd = Conn.CreateCommand();
            


            string query = "SELECT filmeid FROM meufilme where pessoaid='" + id + "' and status='1'";

            List<filmespojo> filmes = new List<filmespojo>();
            List<string> idfilmes = new List<string>();


            //create command and assign the query and connection from the constructor
            cmd.CommandText = query;

            MySqlDataReader Reader = cmd.ExecuteReader();


            while (Reader.Read())
            {
                idfilmes.Add(Reader.GetString(0));


            }
            Reader.Close();
            Reader.Dispose();
            cmd.Dispose();
            objCon.CloseConnection();




            //Execute command
            // cmd.ExecuteNonQuery();

            //close connection
            Conn = objCon.OpenConnection();
            MySqlCommand cmd2 = Conn.CreateCommand();

            for (int i = 0; i < idfilmes.Count; i++)
            {
                string query2 = "SELECT * FROM filmes where cod='" + idfilmes[i] + "'";

                cmd2.CommandText = query2;
                
                MySqlDataReader Reader2 = cmd2.ExecuteReader();

                while (Reader2.Read())
                {
                    filmespojo f = new filmespojo();
                    f.cod = Reader2.GetString(0);
                    f.nome = Reader2.GetString(1);

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models.DAO;
using WebApplication1.Models;
using System.Web.Script.Serialization;
using System.Web.Script;
using Newtonsoft.Json.Linq;


namespace WebApplication1.Controllers
{
    public class FilmesController : Controller
    {
        
        Filme filmes= new Filme();
        // GET: Filmes
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Filme()
        {
            System.Diagnostics.Debug.WriteLine("errado");
            if (Session["user"] == null) { return RedirectToAction("Login","Login"); }
            ViewBag.Message = "Aqui ficam as séries";
            
            List<filmespojo> listar = new List<filmespojo>();
            listar = filmes.listarinfo();


            using (var webClient = new System.Net.WebClient())
            {
                foreach(filmespojo filme in listar)
                {
                    System.Diagnostics.Debug.WriteLine(filme.cod);
                    var jsonData = webClient.DownloadString("http://www.omdbapi.com/?i="+filme.cod+"&apikey=abdc768b");
                    System.Diagnostics.Debug.WriteLine("http://www.omdbapi.com/?i=" + filme.cod + "&apikey=abdc768b");
                    JavaScriptSerializer js = new JavaScriptSerializer();
                    var Dfilme = js.Deserialize <imdbpojo>(jsonData);

                    if (Dfilme.imdbRating != null)
                    {
                        filme.imdbrating = Dfilme.imdbRating;
                    }
                    else filme.imdbrating = "0";
                }

                // ViewBag.CatJson = saida;
            }





            return View(listar);


        }




        public ActionResult filmeremover(filmespojo filmeremover)
        {
            System.Diagnostics.Debug.WriteLine("certo");
           
            filmes.removerfilme(filmeremover);

            return RedirectToAction("Filme");
        }

        public ActionResult Filmeadd()
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            return View();


        }

        [HttpPost]
        public ActionResult Filmeadd(filmespojo filme , HttpPostedFileBase file)
        {
           
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            filme.imagemref = file.FileName;

            if (file != null)
            {
                string pic = System.IO.Path.GetFileName(file.FileName);
                string path = System.IO.Path.Combine(
                                       Server.MapPath("~/img/upload"), pic);

                file.SaveAs(path);



            }

            using (var webClient = new System.Net.WebClient())
            {
                
                    System.Diagnostics.Debug.WriteLine(filme.cod);
                    var jsonData = webClient.DownloadString("http://www.omdbapi.com/?i="+filme.cod+"&apikey=abdc768b");
                    System.Diagnostics.Debug.WriteLine("http://www.omdbapi.com/?i=" + filme.cod + "&apikey=abdc768b");
                    JavaScriptSerializer js = new JavaScriptSerializer();
                    var Dfilme = js.Deserialize <imdbpojo>(jsonData);

                    if (Dfilme.imdbRating != null)
                    {
                        filme.imdbrating = Dfilme.imdbRating;
                        filme.duracao = Dfilme.Runtime;
                        filme.genero = Dfilme.Genre;
                        filme.diretor = Dfilme.Director;
                }
                    else filme.imdbrating = "0";
                

                // ViewBag.CatJson = saida;
            }

                      
           filmes.inserirfilme(filme);



            return RedirectToAction("Filmeadd");


        }



        [HttpPost]
        public ActionResult Filmeeditar(filmespojo filme)
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            System.Diagnostics.Debug.WriteLine(filme.cod);
            
            filmes.atualizarfilme(filme);






            return RedirectToAction("Filme");


        }



        [HttpGet]
        public ActionResult Filmeeditar(filmespojo filmeid, int? x)
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            System.Diagnostics.Debug.WriteLine(filmeid.cod);
           
            filmespojo f = new filmespojo();
            f = filmes.selecionarfilme(filmeid);


            return View(f);


        }

        public ActionResult Assistidos()
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            
            List<filmespojo> f = new List<filmespojo>();
            
            f=filmes.listarassistidos((int)Session["id"]);

            

            return View(f);


        }
        public ActionResult Assistidosremover(filmespojo filmeremover)
        {
            PessoaPojo usuario = new PessoaPojo();
            usuario.Id = (int)Session["id"];
            System.Diagnostics.Debug.WriteLine("certo");

            filmes.removerassistidos(filmeremover,usuario);

            return RedirectToAction("Assistidos");
        }

        public ActionResult Desejos()
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }

            List<filmespojo> f = new List<filmespojo>();
            f = filmes.listardesejos((int)Session["id"]);



            return View(f);


        }
        public ActionResult Desejosremover(filmespojo filmeremover)
        {
            PessoaPojo usuario = new PessoaPojo();
            usuario.Id = (int)Session["id"];
            System.Diagnostics.Debug.WriteLine("certo");

            filmes.removerdesejos(filmeremover,usuario);

            return RedirectToAction("Desejos");
        }

        public ActionResult Inserirassistidos(filmespojo filme)
        {
            PessoaPojo usuario = new PessoaPojo();
            usuario.Id = (int)Session["id"];

           bool verificador= filmes.inserirassistidos(filme,usuario);

            

            return RedirectToAction("Assistidos");
        }

        public ActionResult Inserirdesejos(filmespojo filme)
        {

            PessoaPojo usuario = new PessoaPojo();
            usuario.Id = (int)Session["id"];
            filmes.inserirdesejos(filme,usuario);

            return RedirectToAction("Desejos");
        }

        public ActionResult Serialize()
        {
            List<filmespojo> listar = new List<filmespojo>();

            listar = filmes.listarinfo();

            JavaScriptSerializer js = new JavaScriptSerializer();
            string jsonData = js.Serialize(listar);
            ViewBag.CatJson = jsonData;

            return View();
        }

        public ActionResult Player(filmespojo filme)
        {
            if (Session["user"] == null) { return RedirectToAction("Login", "Login"); }
            System.Diagnostics.Debug.WriteLine(filme.videoref);

            


            return View(filme);


        }

    }
}

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Assistidos.cshtml
@model List<WebApplication1.Models.filmespojo>
@{
    ViewBag.Title = "Assistidos";
    if ((int)Session["nivel"] == 1) { Layout = "~/Views/Shared/_Layoutadm.cshtml"; }
}
<h2>@ViewBag.Title</h2>




<table class="table" cborder="01" bgcolor="#00FF00">
    <tr bgcolor="#FFFFFF">
        <th bgcolor="#FFFFFF">Thumbnail</th>
        <th bgcolor="#FFFFFF">Codigo</th>
        <th bgcolor="#FFFFFF">Nota Imdb</th>
        <th bgcolor="#FFFFFF">Nome</th>
        <th bgcolor="#FFFFFF">Gênero</th>
        <th bgcolor="#FFFFFF">Duração</th>
        <th bgcolor="#FFFFFF">Diretor</th>
        <th bgcolor="#FFFFFF">Ação</th>

    </tr>

    @for (var i = 0; i < Model.Count; i++)
    {
        <tr bgcolor="#FFFFFF">
            <td bgcolor="#FFFFFF"><img src="~/img/upload/@Model[i].imagemref" height="42" width="42"></td>
            <td bgcolor="#FFFFFF">@Model[i].cod</td>
            <td bgcolor="#FFFFFF">@Model[i].imdbrating</td>
            <td bgcolor="#FFFFFF">@Model[i].nome</td>
            <td bgcolor="#FFFFFF">@Model[i].genero</td>
            <td bgcolor="#FFFFFF">@Model[i].duracao</td>
            <td bgcolor="#FFFFFF">@Model[i].diretor</td>
            <left>
                <td bgcolor="#FFFFFF">
                    <left>
                        
                        
                            

                            <a href="@Url.Action("Assistidosremover", "Filmes", new { cod = @Model[i].cod })" class="btn btn-danger " role="button" type="submit"><span class="glyphicon glyphicon-trash"></span></a>

                        


                </td>

        </tr>
    }

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Desejos.cshtml
@model List<WebApplication1.Models.filmespojo>
@{
    ViewBag.Title = "Desejos";
    if ((int)Session["nivel"] == 1) { Layout = "~/Views/Shared/_Layoutadm.cshtml"; }
}
<h2>@ViewBag.Title</h2>




<table class="table" cborder="01" bgcolor="#00FF00">
    <tr bgcolor="#FFFFFF">
        <th bgcolor="#FFFFFF">Thumbnail</th>
        <th bgcolor="#FFFFFF">Codigo</th>
        <th bgcolor="#FFFFFF">Nota Imdb</th>
        <th bgcolor="#FFFFFF">Nome</th>
        <th bgcolor="#FFFFFF">Gênero</th>
        <th bgcolor="#FFFFFF">Duração</th>
        <th bgcolor="#FFFFFF">Diretor</th>
        <th bgcolor="#FFFFFF">Ação</th>

    </tr>

    @for (var i = 0; i < Model.Count; i++)
    {
        <tr bgcolor="#FFFFFF">
            <td bgcolor="#FFFFFF"><img src="~/img/upload/@Model[i].imagemref" height="42" width="42"></td>
            <td bgcolor="#FFFFFF">@Model[i].cod</td>
            <td bgcolor="#FFFFFF">@Model[i].imdbrating</td>
            <td bgcolor="#FFFFFF">@Model[i].nome</td>
            <td bgcolor="#FFFFFF">@Model[i].genero</td>
            <td bgcolor="#FFFFFF">@Model[i].duracao</td>
            <td bgcolor="#FFFFFF">@Model[i].diretor</td>
            <left>
                <td bgcolor="#FFFFFF">
                    <left>



                        <a href="@Url.Action("Inserirassistidos", "Filmes", new { cod = @Model[i].cod })" id=4 class="btn btn-default " role="button">Assistir</a>
                        <a href="@Url.Action("Desejosremover", "Filmes", new { cod = @Model[i].cod })" class="btn btn-danger " role="button" type="submit"><span class="glyphicon glyphicon-trash"></span></a>




                </td>

        </tr>
    }

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Filme.cshtml
@model List <WebApplication1.Models.filmespojo>
@{
    ViewBag.Title = "Filmes";
    if ((int)Session["nivel"] == 1) { Layout = "~/Views/Shared/_Layoutadm.cshtml"; }
}
<h2>@ViewBag.Title</h2>




<table class="table" cborder="01" bgcolor="#00FF00">
    <tr bgcolor="#FFFFFF">
        <th bgcolor="#FFFFFF">Thumbnail</th>
        <th bgcolor="#FFFFFF">Codigo</th>
        <th bgcolor="#FFFFFF">Nota Imdb</th>
        <th bgcolor="#FFFFFF">Nome</th>
        <th bgcolor="#FFFFFF">Gênero</th>
        <th bgcolor="#FFFFFF">Duração</th>
        <th bgcolor="#FFFFFF">Diretor</th>
        
        <th bgcolor="#FFFFFF">Ação</th>


    </tr>
    
    @for (var i = 0; i < Model.Count; i++)
    {
        <tr bgcolor="#FFFFFF">
            <td bgcolor="#FFFFFF"><img src="~/img/upload/@Model[i].imagemref" height="42" width="42"></td>
            <td bgcolor="#FFFFFF">@Model[i].cod</td>
            <td bgcolor="#FFFFFF">@Model[i].imdbrating</td>
            <td bgcolor="#FFFFFF">@Model[i].nome</td>
            <td bgcolor="#FFFFFF">@Model[i].genero</td>
            <td bgcolor="#FFFFFF">@Model[i].duracao</td>
            <td bgcolor="#FFFFFF">@Model[i].diretor</td>
            
            <left>
                <td bgcolor="#FFFFFF"><center>
                    <left>
                        @if ((int)Session["nivel"] == 1)  { 
                            <a href="@Url.Action("filmeeditar", "Filmes", new { cod = @Model[i].cod })" id=4 class="btn btn-info " role="button"><span class="glyphicon glyphicon-pencil"></span></a>

                            <a href="@Url.Action("filmeremover", "Filmes", new { cod = @Model[i].cod })" class="btn btn-danger " role="button" type="submit"><span class="glyphicon glyphicon-trash"></span></a>
                            <br />
                        }

                    <div style=" margin-top:3px;">
    <a href="@Url.Action("Inserirassistidos", "Filmes", new { cod = @Model[i].cod })" id=4 class="btn btn-default " role="button">Assistir</a>
    <a href="@Url.Action("Inserirdesejos", "Filmes", new { cod = @Model[i].cod })" id=4 class="btn btn-default " role="button">Desejo</a>
    <a href="@Url.Action("Player", "Filmes", new { videoref = @Model[i].videoref })" id=4 class="btn btn-default " role="button">Player</a>
</div>
                        </center>
</td>

</tr>
    }

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Filmeadd.cshtml
@{
    ViewBag.Title = "Adcionar Filme";
    if ((int)Session["nivel"] == 1) { Layout = "~/Views/Shared/_Layoutadm.cshtml"; }
}

<form method='POST' class="navbar-form navbar-left" enctype = "multipart/form-data">
    <div style="  width:280px;    position: fixed; left: 50%;    margin-top: 50 px;    margin-left: -130px; opacity:0.8;">
        <h2>@ViewBag.Title</h2>
        <div class="form-group">

            <input style="margin-top:15px;" type='text' class="form-control" name='cod' placeholder="Código" required >
            <br>

            <input style="margin-top:5px;"  type='text' class="form-control" name='nome' placeholder='Nome' required>
            <br>

            <input  style="margin-top:5px;"  type='hidden' value="0" class="form-control" name='genero' placeholder='Gênero' required>
            <br>

            <input style="margin-top:5px;"  type='hidden' value="0" class="form-control" name='duracao' placeholder='Duração (HH:MM:SS)' required>
            <br>

            <input style="margin-top:5px;" type='hidden'value="0" class="form-control" name='diretor' placeholder='Diretor' required>
            <br>
            <input style="margin-top:5px;" type='text' class="form-control" name='videoref' placeholder='Nome do Video' required>
            <br>
            <label for="file">Upload Image:</label>
            <input type="file" name="file" id="file" style="width: 100%;"  required/> 
        

            <center>
        <input style="margin-top:5px;" type='submit' value='enviar' name='btnEnviar' class="btn btn-success"></center>
    </div>
</form>
</div>

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Filmeeditar.cshtml
@model WebApplication1.Models.filmespojo
@{
    ViewBag.Title = "Home Page";
    if ((int)Session["nivel"] == 1) { Layout = "~/Views/Shared/_Layoutadm.cshtml"; }
}

<form method='POST' class="navbar-form navbar-left" >
    <div style="  width:280px;    position: fixed; left: 50%;    margin-top: 50px;    margin-left: -130px; opacity:0.8;">
        <h2>@ViewBag.Title</h2>
        <div class="form-group">

            <input style="margin-top:15px;" type='text' class="form-control" name='cod'  value="@Model.cod" disabled>
            <br>

            <input style="margin-top:5px;" type='text' class="form-control" name='nome' value='@Model.nome' required>
            <br>

            <input style="margin-top:5px;" type='text' class="form-control" name='genero' value='@Model.genero' required>
            <br>

            <input style="margin-top:5px;" type='text' class="form-control" name='duracao' value='@Model.duracao' required>
            <br>

            <input style="margin-top:5px;" type='text' class="form-control" name='diretor' value='@Model.diretor' required>
            <br>

            <input style="margin-top:5px;" type='text' class="form-control" name='videoref' value='@Model.videoref' required>
            <br>


            <center>
                <input style="margin-top:5px;" type='submit' value='enviar' name='btnEnviar' class="btn btn-success">
            </center>
        </div>
</form>
</div>

FOURSTAR -ASP NET/WebApplication1/WebApplication1/Views/Filmes/Serialize.cshtml
@{
    Layout = null;
}

@ViewBag.CatJson